const { Router } = require("express");
const { Collection } = require("./Collection");
const { Cookies } = require("./Cookies");
const { Item } = require("./Item") ;
const router = Router();
const { upload} =require('../middlewares/multer');
const { User } = require("./User");
const { Tag } = require('./Tags');
const { auth } = require('../middlewares/auth');
const { Admin } = require("./Admin");
const {authAdmin} = require('../middlewares/adminAuth')
router.get("/collection", Collection.GET);
router.get("/collection_all", Collection.GET_ALL);
router.get("/my_collections", Collection.GET_BY_USER);
router.get("/one_collection", Collection.GETONE);
router.get("/collection_csv", Collection.GET_CSV);
router.post("/collection",auth, upload.single("img"), Collection.POST);
router.get('/users', User.GET_ALL);
router.get('/user', auth, User.GET);
router.get("/logout", User.LOGOUT);
router.post('/register', User.REGISTER);
router.post("/profile",auth, upload.single("img"), User.UPLOAD_IMAGE);
router.post('/login', User.LOGIN);
router.get("/my_items", Item.GET_BY_USER);
router.get("/item", Item.GET);
router.get("/item_all", Item.GET_ALL);
router.get("/one_item", Item.GETONE);
router.get("/language", Cookies.GET_LANG);
router.get('/theme', Cookies.GET_THEME);
router.get("/tags", Tag.GET);
router.post("/item",auth, upload.single("img"), Item.POST);
router.get("/view_as", auth, authAdmin, Admin.VIEW_AS);
router.put("/user/status", auth,authAdmin, Admin.TOOGLE_USER_STATUS);
router.put("/admin/status", auth, authAdmin, Admin.TOOGLE_ADMIN_STATUS);
router.delete('/user/delete', auth, authAdmin, Admin.DELETE);
module.exports = { router };